name: Build Stunserver

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ubuntu-latest, debian:bullseye, fedora:latest, alpine:latest]
        architecture: [amd64, arm64]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ matrix.platform }}-${{ matrix.architecture }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.platform }}-

      - name: Build and push Docker image
        run: |
          docker buildx build --platform ${{ matrix.platform }} --architecture ${{ matrix.architecture }} -t my-stunserver .
