name: Build Stunserver

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build for Multiple Platforms
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, alpine-latest]
        arch: [amd64, arm64]

    steps:
      # 检查代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 安装依赖
      - name: Install dependencies (Linux)
        if: runner.os != 'Windows'
        run: |
          sudo apt-get update || true
          sudo apt-get install -y build-essential cmake

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install make -y

      # 安装依赖 (Alpine)
      - name: Install dependencies (Alpine)
        if: matrix.os == 'alpine-latest'
        run: |
          apk add --no-cache build-base cmake

      # 编译程序
      - name: Build stunserver
        run: |
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)

      # 保存编译结果
      - name: Archive binaries
        uses: actions/upload-artifact@v3
        with:
          name: stunserver-${{ matrix.os }}-${{ matrix.arch }}
          path: build/stunserver
